BRAINROT_NAMES = [
    "Los Matteos",
    "Bisonte Giuppitere",
    "La Sahur Combinasion",
    "Pot Hotspot",
    "Chicleteira Bicicleteira",
    "La Grande Combinasion",
    "Los Combinasionas",
    "Nuclearo Dinossauro",
    "La Karkerkar Combinasion",
    "Los Hotspotsitos",
    "Tralaledon",
    "Esok Sekolah",
    "La Vacca Saturno Saturnita",
    "Ketupat Kepat",
    "Los Bros",
    "La Supreme Combinasion",
    "Ketchuru and Musturu",
    "Garama and Madundung",
    "Spaghetti Tualetti",
    "Dragon Cannelloni",
    "Secret Lucky Block",
    "Blackhole Goat",
    "Los Spyderinis",
    "Torrtuginni Dragonfrutini",
    "Guerriro Digitale",
    "Karkerkar Kurkur",
    "Sammyni Spyderini",
    "Dul Dul Dul",
    "Chimpanzini Spiderini",
    "Nooo My Hotspot",
    "Other",
    "Extinct Matteo",
    "La Extinct Grande",
    "Los Chicleteiras",
    "Agarrini La Palini",
    "67",
    "Las Sis",
    "Tictac Sahur",
    "Money Money Puggy",
    "To to to Sahur",
    "Tacorita Bicicleta",
    "Mariachi Corazoni",
    "Los Primos",
    "Los Tacoritas",
    "La Spooky Grande",
    "Los Tralaleritos",
    "Los Mobilis",
    "Los 67",
    "Eviledon",
    "Spooky and Pumpky",
    "Mieteteira Bicicleteira",
    "Chillin Chili",
    "Tang Tang Keletang",
    "La Secret Combinasion",
    "La Casa Boo",
    "Burrito Bandito",
    "Las Tralaleritas",
    "Chipso and Queso",
    "Burguro and Fryuro",
    "Job Job Job Sahur",
    "Las Vaquitas Saturnas",
    "Graipuss Medussi"
]